name: mhworld
favicon: null
layout_spectrum: 0.3904344434849918
typography_spectrum: 0.634180863853544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20211423421278596
  lightness: 0.08545905374921858
  saturation: 0.7050272785127163
  rhythmicContrast: 0.4816356608644128
purpose: []
